#!/usr/bin/env python3
"""
知识库下载器
提供知识库完整数据的打包下载功能
"""

import os
import json
import zipfile
import io
from datetime import datetime
from typing import Optional, Dict, Any

def download_knowledge_base_custom(kb_name: str, kb_path: str, options: Dict[str, bool]) -> Optional[bytes]:
    """
    自定义下载知识库数据包
    
    Args:
        kb_name: 知识库名称
        kb_path: 知识库路径
        options: 下载选项字典
    
    Returns:
        压缩包的字节数据，失败返回None
    """
    try:
        if not os.path.exists(kb_path):
            return None
        
        # 创建内存中的ZIP文件
        zip_buffer = io.BytesIO()
        
        with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
            # 1. 添加知识库元数据（如果选择）
            if options.get('include_metadata', True):
                metadata = collect_kb_metadata(kb_name, kb_path)
                zip_file.writestr("metadata.json", json.dumps(metadata, indent=2, ensure_ascii=False))
            
            # 2. 添加向量数据库文件（如果选择）
            if options.get('include_vectors', True):
                add_vector_files(zip_file, kb_path)
            
            # 3. 添加源文档文件（如果选择）
            if options.get('include_docs', True):
                add_source_documents(zip_file, kb_path)
            
            # 4. 添加对话历史（如果选择）
            if options.get('include_history', False):
                add_chat_history(zip_file, kb_name)
            
            # 5. 添加配置文件（如果选择）
            if options.get('include_config', True):
                add_config_files(zip_file, kb_path)
            
            # 6. 添加统计信息（如果选择）
            if options.get('include_stats', True):
                add_statistics(zip_file, kb_path)
            
            # 7. 添加README说明文件
            readme_content = generate_readme(kb_name, options)
            zip_file.writestr("README.md", readme_content)
        
        zip_buffer.seek(0)
        return zip_buffer.getvalue()
        
    except Exception as e:
        print(f"下载知识库失败: {e}")
        return None

def generate_readme(kb_name: str, options: Dict[str, bool]) -> str:
    """生成README说明文件"""
    readme = f"""# 知识库下载包: {kb_name}

## 📦 包含内容

导出时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
导出版本: RAG Pro Max v3.2.7

### 📁 文件结构

"""
    
    if options.get('include_metadata', True):
        readme += "- `metadata.json` - 知识库元数据信息\n"
    
    if options.get('include_vectors', True):
        readme += "- `vectors/` - 向量数据库文件\n"
    
    if options.get('include_docs', True):
        readme += "- `documents/` - 源文档文件\n"
    
    if options.get('include_config', True):
        readme += "- `config/` - 配置文件\n"
    
    if options.get('include_history', False):
        readme += "- `chat_history.json` - 对话历史记录\n"
    
    if options.get('include_stats', True):
        readme += "- `statistics.json` - 统计信息\n"
    
    readme += f"""
## 🔄 恢复说明

1. 解压此文件到 RAG Pro Max 的 `vector_db_storage` 目录
2. 重启应用程序
3. 在知识库列表中选择恢复的知识库

## ⚠️ 注意事项

- 此下载包包含知识库的完整数据
- 请妥善保管，避免数据泄露
- 恢复时请确保目标环境兼容

---
Generated by RAG Pro Max v3.2.7
"""
    
    return readme

def download_knowledge_base(kb_name: str, kb_path: str) -> Optional[bytes]:
    """
    下载知识库完整数据包
    
    Args:
        kb_name: 知识库名称
        kb_path: 知识库路径
    
    Returns:
        压缩包的字节数据，失败返回None
    """
    try:
        if not os.path.exists(kb_path):
            return None
        
        # 创建内存中的ZIP文件
        zip_buffer = io.BytesIO()
        
        with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
            # 1. 添加知识库元数据
            metadata = collect_kb_metadata(kb_name, kb_path)
            zip_file.writestr("metadata.json", json.dumps(metadata, indent=2, ensure_ascii=False))
            
            # 2. 添加向量数据库文件
            add_vector_files(zip_file, kb_path)
            
            # 3. 添加源文档文件
            add_source_documents(zip_file, kb_path)
            
            # 4. 添加对话历史
            add_chat_history(zip_file, kb_name)
            
            # 5. 添加配置文件
            add_config_files(zip_file, kb_path)
            
            # 6. 添加统计信息
            add_statistics(zip_file, kb_path)
        
        zip_buffer.seek(0)
        return zip_buffer.getvalue()
        
    except Exception as e:
        print(f"下载知识库失败: {e}")
        return None

def collect_kb_metadata(kb_name: str, kb_path: str) -> Dict[str, Any]:
    """收集知识库元数据"""
    metadata = {
        "name": kb_name,
        "path": kb_path,
        "export_time": datetime.now().isoformat(),
        "version": "3.2.7",
        "type": "RAG_Knowledge_Base"
    }
    
    # 添加知识库统计信息
    try:
        stats = get_kb_statistics(kb_path)
        metadata.update(stats)
    except:
        pass
    
    return metadata

def add_vector_files(zip_file: zipfile.ZipFile, kb_path: str):
    """添加向量数据库文件"""
    vector_extensions = ['.json', '.pkl', '.index', '.faiss', '.chroma']
    
    for root, dirs, files in os.walk(kb_path):
        for file in files:
            file_path = os.path.join(root, file)
            file_ext = os.path.splitext(file)[1].lower()
            
            # 添加向量相关文件
            if file_ext in vector_extensions or 'vector' in file.lower() or 'index' in file.lower():
                rel_path = os.path.relpath(file_path, kb_path)
                zip_file.write(file_path, f"vectors/{rel_path}")

def add_source_documents(zip_file: zipfile.ZipFile, kb_path: str):
    """添加源文档文件"""
    doc_extensions = ['.pdf', '.docx', '.txt', '.md', '.html', '.xlsx', '.pptx']
    
    # 查找源文档目录
    source_dirs = ['documents', 'docs', 'source', 'files']
    
    for root, dirs, files in os.walk(kb_path):
        for file in files:
            file_path = os.path.join(root, file)
            file_ext = os.path.splitext(file)[1].lower()
            
            # 添加文档文件
            if file_ext in doc_extensions:
                rel_path = os.path.relpath(file_path, kb_path)
                zip_file.write(file_path, f"documents/{rel_path}")

def add_chat_history(zip_file: zipfile.ZipFile, kb_name: str):
    """添加对话历史"""
    try:
        # 检查用户上下文
        import streamlit as st
        if hasattr(st, 'session_state') and 'user_context' in st.session_state:
            from src.auth.user_context import UserContext
            chat_path = UserContext.get_user_chat_path(kb_name)
        else:
            chat_path = f"chat_histories/{kb_name}.json"
        
        if os.path.exists(chat_path):
            zip_file.write(chat_path, "chat_history.json")
    except:
        # 向后兼容
        chat_path = f"chat_histories/{kb_name}.json"
        if os.path.exists(chat_path):
            zip_file.write(chat_path, "chat_history.json")

def add_config_files(zip_file: zipfile.ZipFile, kb_path: str):
    """添加配置文件"""
    config_files = ['config.json', 'settings.json', 'manifest.json', 'info.json']
    
    for config_file in config_files:
        config_path = os.path.join(kb_path, config_file)
        if os.path.exists(config_path):
            zip_file.write(config_path, f"config/{config_file}")

def add_statistics(zip_file: zipfile.ZipFile, kb_path: str):
    """添加统计信息"""
    try:
        stats = get_detailed_statistics(kb_path)
        zip_file.writestr("statistics.json", json.dumps(stats, indent=2, ensure_ascii=False))
    except:
        pass

def get_kb_statistics(kb_path: str) -> Dict[str, Any]:
    """获取知识库基础统计信息"""
    stats = {
        "total_files": 0,
        "total_size": 0,
        "created_time": None,
        "modified_time": None
    }
    
    try:
        if os.path.exists(kb_path):
            stats["created_time"] = datetime.fromtimestamp(os.path.getctime(kb_path)).isoformat()
            stats["modified_time"] = datetime.fromtimestamp(os.path.getmtime(kb_path)).isoformat()
            
            for root, dirs, files in os.walk(kb_path):
                stats["total_files"] += len(files)
                for file in files:
                    file_path = os.path.join(root, file)
                    if os.path.exists(file_path):
                        stats["total_size"] += os.path.getsize(file_path)
    except:
        pass
    
    return stats

def get_detailed_statistics(kb_path: str) -> Dict[str, Any]:
    """获取详细统计信息"""
    stats = {
        "export_info": {
            "timestamp": datetime.now().isoformat(),
            "kb_path": kb_path,
            "export_version": "3.2.7"
        },
        "file_breakdown": {},
        "directory_structure": []
    }
    
    try:
        # 文件类型统计
        file_types = {}
        dir_structure = []
        
        for root, dirs, files in os.walk(kb_path):
            rel_root = os.path.relpath(root, kb_path)
            if rel_root != '.':
                dir_structure.append(rel_root)
            
            for file in files:
                ext = os.path.splitext(file)[1].lower()
                if ext not in file_types:
                    file_types[ext] = {"count": 0, "size": 0}
                
                file_path = os.path.join(root, file)
                if os.path.exists(file_path):
                    file_size = os.path.getsize(file_path)
                    file_types[ext]["count"] += 1
                    file_types[ext]["size"] += file_size
        
        stats["file_breakdown"] = file_types
        stats["directory_structure"] = sorted(dir_structure)
        
    except Exception as e:
        stats["error"] = str(e)
    
    return stats
